package com.damdamdeo.todo.publicfrontend;

import com.jayway.restassured.module.jsv.JsonSchemaValidator;
import io.quarkus.test.junit.QuarkusTest;
import org.hamcrest.Matchers;
import org.junit.jupiter.api.Test;

import javax.ws.rs.core.MediaType;

import java.util.UUID;
import java.util.concurrent.TimeUnit;

import static io.restassured.RestAssured.given;
import static org.awaitility.Awaitility.await;
import static org.hamcrest.core.IsEqual.equalTo;

@QuarkusTest
public class TodoEnpointTest extends AbstractTodoTest {

    private static final UUID nullUUID = UUID.fromString("00000000-0000-0000-0000-000000000000");

    @Test
    public void should_api_create_todo() {
        final String autoGeneratedTodoId = given()
                .param("description", "lorem ipsum")
                .when()
                .log().all()
                .post("/todos/createNewTodo")
                .then().log().all()
                .statusCode(200)
                .body(JsonSchemaValidator.matchesJsonSchemaInClasspath("expected/todo.json"))
                .body("description", equalTo("lorem ipsum"))
                .body("todoStatus", equalTo("IN_PROGRESS"))
                .body("version", equalTo(0))
                .body("canMarkTodoAsCompleted", equalTo(true))
                .extract()
                .path("todoId");
        await().atMost(10, TimeUnit.SECONDS).until(() ->
                given().when().get(String.format("/todos/%s", autoGeneratedTodoId)).statusCode() == 200
        );
        given()
                .when()
                .get(String.format("/todos/%s", autoGeneratedTodoId))
                .then().log().all()
                .statusCode(200)
                .body(JsonSchemaValidator.matchesJsonSchemaInClasspath("expected/todo.json"))
                .body("todoId", equalTo(autoGeneratedTodoId))
                .body("description", equalTo("lorem ipsum"))
                .body("todoStatus", equalTo("IN_PROGRESS"))
                .body("version", equalTo(0))
                .body("canMarkTodoAsCompleted", equalTo(true));
        given()
                .get("/todos")
                .then()
                .log().all()
                .statusCode(200)
                .body("$.size()", equalTo(1))
                .body("[0].todoId", equalTo(autoGeneratedTodoId))
                .body("[0].description", equalTo("lorem ipsum"))
                .body("[0].todoStatus", equalTo("IN_PROGRESS"))
                .body("[0].canMarkTodoAsCompleted", equalTo(true))
                .body("[0].version", equalTo(0));
    }

    @Test
    public void should_api_mark_todo_as_completed() {
        final String autoGeneratedTodoId = given()
                .param("description", "lorem ipsum")
                .when()
                .post("/todos/createNewTodo")
                .then()
                .statusCode(200)
                .extract()
                .path("todoId");

        given()
                .param("todoId", autoGeneratedTodoId)
                .when()
                .post("/todos/markTodoAsCompleted")
                .then()
                .statusCode(200)
                .body(JsonSchemaValidator.matchesJsonSchemaInClasspath("expected/todo.json"))
                .body("todoId", equalTo(autoGeneratedTodoId))
                .body("description", equalTo("lorem ipsum"))
                .body("todoStatus", equalTo("COMPLETED"))
                .body("version", equalTo(1))
                .body("canMarkTodoAsCompleted", equalTo(false));
    }

    @Test
    public void should_api_handle_exception_from_remote_service() {
        given()
                .when()
                .get(String.format("/todos/%s", nullUUID.toString()))
                .then()
                .statusCode(404)
                .contentType(MediaType.TEXT_PLAIN)
                .body(Matchers.equalTo(String.format("Le todoId '%s' est inconnu.", nullUUID.toString())));
    }

}
