apiVersion: v1
kind: Template
labels:
  template: mailhog-template
metadata:
  annotations:
    description: |-
      MailHog local SMTP server
    openshift.io/display-name: MailHog
    openshift.io/long-description: This template provides a local SMTP server.
    openshift.io/provider-display-name: Damdamdeo
    tags: smtp,server
  name: mailhog
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: mailhog
    spec:
      ports:
        - name: smtp
          nodePort: 0
          port: 1025
          protocol: TCP
          targetPort: 1025
        - name: web
          nodePort: 0
          port: 8025
          protocol: TCP
          targetPort: 8025
      selector:
        name: mailhog
      sessionAffinity: None
    status:
      loadBalancer: {}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: mailhog
    spec:
      port:
        targetPort: web
      to:
        kind: Service
        name: mailhog
        weight: 100
      wildcardPolicy: None
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        template.alpha.openshift.io/wait-for-ready: 'true'
      name: mailhog
      labels:
        app: mailhog
    spec:
      replicas: 1
      selector:
        name: mailhog
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: mailhog
        spec:
          containers:
            - capabilities: {}
              image: mailhog/mailhog:v1.0.0
              imagePullPolicy: IfNotPresent
              livenessProbe:
                httpGet:
                  path: /api/v1/messages
                  port: 8025
                initialDelaySeconds: 5
                timeoutSeconds: 10
              name: mailhog
              ports:
                - containerPort: 1025
                  protocol: TCP
                - containerPort: 8025
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /api/v1/messages
                  port: 8025
                initialDelaySeconds: 2
                timeoutSeconds: 1
              resources:
                limits:
                  memory: 32Mi
              securityContext:
                capabilities: {}
                privileged: false
              terminationMessagePath: "/dev/termination-log"
          dnsPolicy: ClusterFirst
          restartPolicy: Always
