apiVersion: v1
kind: Template
labels:
  template: maven-pvc-template
metadata:
  name: maven-pvc-template
objects:
  - apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    metadata:
      name: "maven-pvc"
      namespace: "kubernetes-plugin"
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
