kind: BuildConfig
apiVersion: v1
metadata:
  name: todo-write-app-pipeline
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        try {
           timeout(time: 20, unit: 'MINUTES') {
              node("jenkins-agent-maven-35-graalvm-centos7") {
                stage("Checkout") {
                  git url: "https://github.com/dcdh/eventstore-quarkus-sample-app.git", branch: "master"
                }
                stage("Build native") {
                  sh "mvn package -Pnative"

                }
              }
           }
        } catch (err) {
           echo "in catch block"
           echo "Caught: ${err}"
           currentBuild.result = 'FAILURE'
           throw err
        }
      type: JenkinsPipeline
