apiVersion: v1
kind: Template
labels:
  template: todo-write-app-template
metadata:
  name: todo-write-app
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: todo-write-app
    spec:
      ports:
        - name: web
          nodePort: 0
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        name: todo-write-app
      sessionAffinity: None
    status:
      loadBalancer: {}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: todo-write-app
    spec:
      port:
        targetPort: web
      to:
        kind: Service
        name: todo-write-app
        weight: 100
      wildcardPolicy: None
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        template.alpha.openshift.io/wait-for-ready: 'true'
      name: todo-write-app
      labels:
        app: todo-write-app
    spec:
      replicas: 1
      selector:
        name: todo-write-app
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: todo-write-app
        spec:
          initContainers:
            - name: init-debezium-connector
              image: centos:8
              env:
                - name: OPENSHIFT_NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
              command: ["sh", "-c", "curl -i -X POST -H 'Accept:application/json' -H 'Content-Type:application/json' http://debezium-connect-api.$(OPENSHIFT_NAMESPACE).svc:8083/connectors/ -d '{\"name\": \"todo-connector\", \"config\": {\"connector.class\": \"io.debezium.connector.postgresql.PostgresConnector\", \"tasks.max\": \"1\", \"database.hostname\": \"eventstore.$(OPENSHIFT_NAMESPACE).svc\", \"database.port\": \"5432\", \"database.user\": \"postgresuser\", \"database.password\": \"postgrespassword\", \"database.dbname\" : \"eventstore\", \"database.server.name\": \"eventstore.$(OPENSHIFT_NAMESPACE).svc\", \"schema.whitelist\": \"public\", \"transforms\": \"route\", \"transforms.route.type\": \"org.apache.kafka.connect.transforms.RegexRouter\", \"transforms.route.regex\": \"([^.]+)\\\\.([^.]+)\\\\.([^.]+)\", \"transforms.route.replacement\": \"$3\"}}'"]
          containers:
            - capabilities: {}
              image: " "
              env:
                - name: OPENSHIFT_NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
                - name: JAVA_OPTIONS
                  value: >-
                    -Dquarkus.http.host=0.0.0.0
                    -Djava.util.logging.manager=org.jboss.logmanager.LogManager
                    -Dquarkus.datasource.url=jdbc:postgresql://eventstore.$(OPENSHIFT_NAMESPACE).svc:5432/eventstore
                    -Dquarkus.http.port=8080
                    -Dquarkus.datasource.username=postgresuser
                    -Dquarkus.datasource.password=postgrespassword
                    -Xmx256m
              imagePullPolicy: IfNotPresent
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 5
                timeoutSeconds: 10
              name: todo-write-app
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 2
                timeoutSeconds: 1
              resources:
                limits:
                  memory: 256Mi
              securityContext:
                capabilities: {}
                privileged: false
              terminationMessagePath: "/dev/termination-log"
          dnsPolicy: ClusterFirst
          restartPolicy: Always
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - todo-write-app
            from:
              kind: ImageStreamTag
              name: todo-write-app:latest
            lastTriggeredImage: ''
          type: ImageChange
        - type: ConfigChange