apiVersion: v1
kind: Template
labels:
  template: todo-graph-visualiser-app-template
metadata:
  name: todo-graph-visualiser-app
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: todo-graph-visualiser-app
    spec:
      ports:
        - name: web
          nodePort: 0
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        name: todo-graph-visualiser-app
      sessionAffinity: None
    status:
      loadBalancer: {}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: todo-graph-visualiser-app
    spec:
      port:
        targetPort: web
      to:
        kind: Service
        name: todo-graph-visualiser-app
        weight: 100
      wildcardPolicy: None
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        template.alpha.openshift.io/wait-for-ready: 'true'
      name: todo-graph-visualiser-app
      labels:
        app: todo-graph-visualiser-app
    spec:
      replicas: 1
      selector:
        name: todo-graph-visualiser-app
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: todo-graph-visualiser-app
        spec:
          containers:
            - capabilities: {}
              image: " "
              env:
                - name: OPENSHIFT_NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
                - name: JAVA_OPTIONS
                  value: >-
                    -Dquarkus.http.host=0.0.0.0
                    -Djava.util.logging.manager=org.jboss.logmanager.LogManager
                    -Dsmallrye.messaging.source.event.bootstrap.servers=broker-kafka-bootstrap.$(OPENSHIFT_NAMESPACE).svc:9092
                    -Dsmallrye.messaging.source.aggregateroot.bootstrap.servers=broker-kafka-bootstrap.$(OPENSHIFT_NAMESPACE).svc:9092
                    -Dquarkus.neo4j.uri=bolt://neo4j.$(OPENSHIFT_NAMESPACE).svc:7687
                    -Dquarkus.neo4j.authentication.username=neo4j
                    -Dquarkus.neo4j.authentication.password=secret
                    -Xmx256m
              imagePullPolicy: IfNotPresent
              livenessProbe:
                httpGet:
                  path: /health/live
                  port: 8080
                initialDelaySeconds: 5
                timeoutSeconds: 10
              name: todo-graph-visualiser-app
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /health/ready
                  port: 8080
                initialDelaySeconds: 2
                timeoutSeconds: 1
              resources:
                limits:
                  memory: 256Mi
              securityContext:
                capabilities: {}
                privileged: false
              terminationMessagePath: "/dev/termination-log"
          dnsPolicy: ClusterFirst
          restartPolicy: Always
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - todo-graph-visualiser-app
            from:
              kind: ImageStreamTag
              name: todo-graph-visualiser-app:latest
            lastTriggeredImage: ''
          type: ImageChange
        - type: ConfigChange
